# Generated by Django 4.0.3 on 2023-07-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openapi', '0002_init_setting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='init_setting',
        ),
    ]
